# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' HMC sampler for competition model
#' 
#' @name HMC
#' @param Labels List of vectors containing labels containing membership of spike for AB trials
#' @param X_A List of vectors containing ISIs for A trials
#' @param X_B List of vectors containing ISIs for B trials
#' @param X_AB List of vectors containing ISIs for AB trials
#' @param n_A Vector containing number of spikes per trial for A stimulus trials
#' @param n_B Vector containing number of spikes per trial for B stimulus trials
#' @param n_AB Vector containing number of spikes per trial for AB stimulus trials
#' @param MCMC_iters Integer containing number of HMC iterations
#' @param init_position Vector containing starting position for HMC
#' @param Leapfrog_steps Integer containing number of leapfrog steps for approximating the Hamiltonian dynamics
#' @param I_A_shape Double containing shape parameter for prior distribution on I_A
#' @param I_A_rate Double containing rate parameter for prior distribution on I_A
#' @param I_B_shape Double containing shape parameter for prior distribution on I_B
#' @param I_B_rate Double containing rate parameter for prior distribution on I_B
#' @param sigma_A_mean Double containing mean parameter for prior distribution on sigma_A
#' @param sigma_A_shape Double containing shape parameter for prior distribution on sigma_A
#' @param sigma_B_mean Double containing mean parameter for prior distribution on sigma_B
#' @param sigma_B_shape Double containing shape parameter for prior distribution on sigma_B
#' @param delta_shape Double containing shape parameter for prior distribution on delta
#' @param delta_rate Double containing rate parameter for prior distribution on delta
#' @param eps_step Vector containing step size for approximating gradient
#' @param step_size Vector containing step size for leapfrog integrator
#' 
#' @export
HMC <- function(Labels, X_A, X_B, X_AB, n_A, n_B, n_AB, MCMC_iters, Warm_block = 500L, init_position = NULL, Leapfrog_steps = 10L, I_A_shape = 40, I_A_rate = 1, I_B_shape = 40, I_B_rate = 1, sigma_A_mean = 6.32, sigma_A_shape = 1, sigma_B_mean = 6.32, sigma_B_shape = 1, delta_shape = 0.5, delta_rate = 0.1, eps_step = NULL, step_size = 0.001, step_size_delta = 0.00005, Mass_mat = NULL) {
    .Call('_NeuralComp_HMC', PACKAGE = 'NeuralComp', Labels, X_A, X_B, X_AB, n_A, n_B, n_AB, MCMC_iters, Warm_block, init_position, Leapfrog_steps, I_A_shape, I_A_rate, I_B_shape, I_B_rate, sigma_A_mean, sigma_A_shape, sigma_B_mean, sigma_B_shape, delta_shape, delta_rate, eps_step, step_size, step_size_delta, Mass_mat)
}

#' MH sampler for labels
Sample_Labels <- function(X_AB, n_AB, MCMC_iters, theta) {
    .Call('_NeuralComp_Sample_Labels', PACKAGE = 'NeuralComp', X_AB, n_AB, MCMC_iters, theta)
}

GetTraceLabels <- function(MCMC_output, sample_num, MCMC_iters) {
    .Call('_NeuralComp_GetTraceLabels', PACKAGE = 'NeuralComp', MCMC_output, sample_num, MCMC_iters)
}

posterior_Z1 <- function(Labels, X_AB, theta, spike_num, n_AB) {
    .Call('_NeuralComp_posterior_Z1', PACKAGE = 'NeuralComp', Labels, X_AB, theta, spike_num, n_AB)
}

Sampler <- function(X_A, X_B, X_AB, n_A, n_B, n_AB, MCMC_iters, Warm_block = 500L, init_position = NULL, Leapfrog_steps = 10L, I_A_shape = 40, I_A_rate = 1, I_B_shape = 40, I_B_rate = 1, sigma_A_mean = 6.32, sigma_A_shape = 1, sigma_B_mean = 6.32, sigma_B_shape = 1, delta_shape = 0.5, delta_rate = 0.1, eps_step = NULL, step_size = 0.001, step_size_delta = 0.00005, step_size_labels = 0.0001, num_evals = 10000L, prior_p_labels = 0.5, Mass_mat = NULL) {
    .Call('_NeuralComp_Sampler', PACKAGE = 'NeuralComp', X_A, X_B, X_AB, n_A, n_B, n_AB, MCMC_iters, Warm_block, init_position, Leapfrog_steps, I_A_shape, I_A_rate, I_B_shape, I_B_rate, sigma_A_mean, sigma_A_shape, sigma_B_mean, sigma_B_shape, delta_shape, delta_rate, eps_step, step_size, step_size_delta, step_size_labels, num_evals, prior_p_labels, Mass_mat)
}

approx_trans_p <- function(step_size, num_evals, theta) {
    .Call('_NeuralComp_approx_trans_p', PACKAGE = 'NeuralComp', step_size, num_evals, theta)
}

backward_sim1 <- function(Prob_mat, theta, X_AB, step_size, num_evals) {
    .Call('_NeuralComp_backward_sim1', PACKAGE = 'NeuralComp', Prob_mat, theta, X_AB, step_size, num_evals)
}

FFBS_labels <- function(X_AB, n_AB, theta, step_size, num_evals, prior_p_labels, MCMC_iters) {
    .Call('_NeuralComp_FFBS_labels', PACKAGE = 'NeuralComp', X_AB, n_AB, theta, step_size, num_evals, prior_p_labels, MCMC_iters)
}

calc_gradient1 <- function(Labels, theta, X_A, X_B, X_AB, n_A, n_B, n_AB, I_A_shape, I_A_rate, I_B_shape, I_B_rate, sigma_A_mean, sigma_A_shape, sigma_B_mean, sigma_B_shape, delta_shape, delta_rate, eps_step) {
    .Call('_NeuralComp_calc_gradient1', PACKAGE = 'NeuralComp', Labels, theta, X_A, X_B, X_AB, n_A, n_B, n_AB, I_A_shape, I_A_rate, I_B_shape, I_B_rate, sigma_A_mean, sigma_A_shape, sigma_B_mean, sigma_B_shape, delta_shape, delta_rate, eps_step)
}

log_likelihood1 <- function(Labels, theta, X_A, X_B, X_AB, n_A, n_B, n_AB) {
    .Call('_NeuralComp_log_likelihood1', PACKAGE = 'NeuralComp', Labels, theta, X_A, X_B, X_AB, n_A, n_B, n_AB)
}

rinv_gauss1 <- function(mean, shape) {
    .Call('_NeuralComp_rinv_gauss1', PACKAGE = 'NeuralComp', mean, shape)
}

r_multinomial <- function(prob) {
    .Call('_NeuralComp_r_multinomial', PACKAGE = 'NeuralComp', prob)
}

FFBS_ensemble <- function(X_AB, n_AB, theta, MCMC_iters, step_size = 0.0001, num_evals = 10000L, delta_proposal_mean = 0.05, delta_proposal_shape = 0.05, M_proposal = 10L, delta_shape = 0.5, delta_rate = 0.1) {
    .Call('_NeuralComp_FFBS_ensemble', PACKAGE = 'NeuralComp', X_AB, n_AB, theta, MCMC_iters, step_size, num_evals, delta_proposal_mean, delta_proposal_shape, M_proposal, delta_shape, delta_rate)
}

prior_Labels1 <- function(n_AB, trans_prob_0, trans_prob) {
    .Call('_NeuralComp_prior_Labels1', PACKAGE = 'NeuralComp', n_AB, trans_prob_0, trans_prob)
}

calc_log_sum1 <- function(x) {
    .Call('_NeuralComp_calc_log_sum1', PACKAGE = 'NeuralComp', x)
}

rcpparma_hello_world <- function() {
    .Call('_NeuralComp_rcpparma_hello_world', PACKAGE = 'NeuralComp')
}

rcpparma_outerproduct <- function(x) {
    .Call('_NeuralComp_rcpparma_outerproduct', PACKAGE = 'NeuralComp', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_NeuralComp_rcpparma_innerproduct', PACKAGE = 'NeuralComp', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_NeuralComp_rcpparma_bothproducts', PACKAGE = 'NeuralComp', x)
}

dinv_gauss <- function(x, mean, shape) {
    .Call('_NeuralComp_dinv_gauss', PACKAGE = 'NeuralComp', x, mean, shape)
}

pinv_gauss <- function(x, mean, shape) {
    .Call('_NeuralComp_pinv_gauss', PACKAGE = 'NeuralComp', x, mean, shape)
}

dnorm_test <- function(prop_momentum) {
    .Call('_NeuralComp_dnorm_test', PACKAGE = 'NeuralComp', prop_momentum)
}

